HashTableClassChainingC++
jeremie1112/All_Programs_and_algorithms pull request #194
Opened 2022-10-03 07:00 UTC by VINAYBOYAT11

2022-10-03 16:36 UTC, jeremie1112 requested changes
Hello,
Please read contribution.md and add the program in the respective path.
After that i'll accept your PR

2022-10-04 08:20 UTC, VINAYBOYAT11 commented
[@jeremie1112] check out my pull request

2022-10-04 08:22 UTC, VINAYBOYAT11 commented on Data_structures/Hashing/c++/all_hashing_oprations.c++
> +I would also suggest you try other collision handling algorithms and different hash functions on this Hash Table and test their performance./*
[comment box]

2022-10-04 08:48 UTC, jeremie1112 requested changes
Hello,
Can I ask you if this code was written by you ?
Also, the file name is not correct. It should be .cpp and not .c++

2022-10-04 09:05 UTC, VINAYBOYAT11 commented
no , am here just  contrubuting this code, it might help others 
and sorry  for that mistake ,i accendentily mistyped

2022-10-04 09:10 UTC, VINAYBOYAT11 commented
no ,but i understand this code and that why i contrubuting this code, it might help others
and sorry for that mistake ,i accendentily mistyped

2022-10-04 09:17 UTC, jeremie1112 approved these changes
Thanks for changes.
It's good now

2022-10-04 09:17 UTC, jeremie1112 commented
I understand, I really hope you understand this code and thank you for sharing

2022-10-04 09:18 UTC, merged

2022-10-04 09:25 UTC, VINAYBOYAT11 commented
ayy @jeremie1112   this is my first hactoberfest so 
thankyou sooo much ,for accepting my code and mentorship also..
am glad to meet you .